#!/system/bin/sh
#SD-Card Tweaks
#Requires reboot!!! Increase read ahead buffer:
#Off

echo "Configured by boeffla tweaks app" > /data/boeffla-sdcardtweak-off

# Display dialog window

if [ ! -f /system/etc/init.d/S65enable_001bksdcard_005-off ]; then

	rm /sdcard/boeffla_twk_dlg_helper

	am start -a android.intent.action.MAIN -e message "SD-Card tweak changed, please reboot for settings to take effect." -e title "SD-Card Tweak" -e okstyle "Ok" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

	while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
	do
		/sbin/busybox sleep 1
	done

	rm /sdcard/boeffla_twk_dlg_helper

fi
