#!/system/bin/sh
#Android Logger
#Requires reboot!!! Enable or disable Android Logger:
#Off (default)

/sbin/busybox rm /data/boeffla-alogger

# Display dialog window (default, so no special handling for init.d script required)

rm /sdcard/boeffla_twk_dlg_helper

am start -a android.intent.action.MAIN -e message "Android logger will be disabled after reboot." -e title "Android Logger" -e okstyle "Ok" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
	/sbin/busybox sleep 1
done

rm /sdcard/boeffla_twk_dlg_helper
