#!/system/bin/sh
#Android Logger
#Requires reboot!!! Enable or disable Android Logger:
#On

echo "Configured by boeffla tweaks app" > /data/boeffla-alogger

# Display dialog window

if [ ! -f /system/etc/init.d/S70enable_001bkalogger_005-on ]; then

	rm /sdcard/boeffla_twk_dlg_helper

	am start -a android.intent.action.MAIN -e message "Android logger will be enabled after reboot." -e title "Android Logger" -e okstyle "Ok" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

	while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
	do
		/sbin/busybox sleep 1
	done

	rm /sdcard/boeffla_twk_dlg_helper

fi
